---
sudo: required
language: python
services:
  - docker

before_install:
  - docker pull krig/crmsh:latest
  - docker run --mount type=bind,source="$(pwd)",target=/app krig/crmsh /bin/sh -c "cd /app; ./autogen.sh; ./configure --prefix /usr; make; make install; /usr/share/crmsh/tests/regression.sh"

after_failure:
  - sudo cat $TRAVIS_BUILD_DIR/crmtestout/regression.out $TRAVIS_BUILD_DIR/crmtestout/crm.*
