---
sudo: required
language: python
services:
  - docker

before_install:
  - docker pull krig/crmsh:latest
  - docker run -t -v $(pwd):/app krig/crmsh /bin/sh -c "cd /app; ./autogen.sh; ./configure --prefix /usr; make install; sh -x /usr/share/crmsh/tests/regression.sh"

after_failure:
  - sudo cat $TRAVIS_BUILD_DIR/crmtestout/regression.out $TRAVIS_BUILD_DIR/crmtestout/crm.*
