---
sudo: false
language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install -r requirements.txt"
script: ./test/run --with-coverage
notifications:
  irc:
    channels:
      - "chat.freenode.net#clusterlabs-dev"
    on_success: never
    on_failure: change
